# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57f88825361764190c233ccc64d352e76bc97abef65938d54a66e224394b8c656e6602b83d16a1ae135317c2353a5ac3e160dcd157e47d000086a14b71be1c46
  pubnub_subscribe_key: sub-c-8b483e74-ec05-11e5-8f88-0619f8945a4f
  pubnub_publish_key: pub-c-34c27d00-69c1-411e-8a2f-bd6611f653d6
  pubnub_secret_key: sub-c-8b483e74-ec05-11e5-8f88-0619f8945a4f
test:
  secret_key_base: f200908236260dc0f94e3bd28faf865848996967a88a46acbd2f1c8fe6f999e3abba42088d3b74c8a2558fc66061282a21bbd897ae7d50842ef1e3636a754e4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
